package com.smu.vaan.model.security;

public enum AuthorityName {
    ROLE_ANONYMOUS,
    ROLE_STORAGE_USER,
    ROLE_AGENT_USER,
    ROLE_ADVANCE_USER,
    ROLE_AGENT_UPLOADER,
    ROLE_STORAGE_UPLOADER,
    ROLE_ADMIN,
    ROLE_AGENT_EMPLOYEE,
    ROLE_STORAGE_EMPLOYEE,
    ROLE_STORAGE_STAT
}